### ISSUE TITLE
Add lando

### ISSUE THREAD

**Issue by mattpaz** [beatcracker/toptout#441]
https://docs.lando.dev/help/data.html#tl-dr

```
If you would like to opt-out you can do so by adding the following to your Lando global config

stats:
  - report: false
    url: https://metrics.lando.dev

```
